### PR TITLE
DEM updates

### PR DESCRIPTION
**Pull request by danfos**
The commit description should say it, on the reason why allowing negative minimum heights in the DEM layer, parts of the Netherlands is below sea-level.

### CODE REVIEW

**Comment by rnorris** [comment]
Thanks for the continued interest.

1. Remove debug printf
- I will apply this.

2. Fix whitespace: replace tab by spaces
- Agreed it's kind of annoying that some files have inconsistent whitespacing. It's more than just vikdemlayer.c file though.
I've often thought about applying some auto indent to the code for consistency, but however I decided that being able to see who and when initially wrote the code via a clean source code history (e.g. just git blame if possible, rather than having to sift back through commits) was preferable.
Thus I won't be applying this

3. Allow for negative minimum heights in the DEM layer
- Some of England is also lower than the sea too - particularly Norfolk & 'The Wash'
Unfortunately this code doesn't maintain the current behaviour - the 'sea' turns brown when using a value of 0 (which is also the default)

Maybe the test on line 682 needs to be '<=' so that the min_elev value is included in the 'below_minimum' range? Albeit 'below_minimum' is then not an accurate variable name - may be rename that to 'minimum_level' or similar.

Note DEM values over sea is 0, just as it can be on land - so from DEM information one can not really distinguish between land and sea. But it's nice to have the option to draw a pseudo sea.

**Comment by danfos** [comment]
On 2) I see your point. On the other hand, annotating for a past tag (git annotate <hash>^) is easy enough, on my job the code was once fixed for spacing and I regularly do that. No problem dropping it though.

Good catch about blue for sea, yes changing < to <= will do the trick and by inverting the below_minimum variable and calling it above_minimum I think the code remains readable, let me try to update the patch on this.

**Comment by rnorris** [comment]
Allow for negative minimum heights in the DEM layer functionality has (finally!) been added into the source code.

**Comment by danfos** [comment]
Thanks for merging!

**Comment by danfos** [comment]
Thanks for merging!

**Pull request closed without merging**
