### PR TITLE
Add splicer tool

### PR DESCRIPTION
**Pull request by yourealwaysbe**
Used when editing track/routes to change segments of the track/route.
It's probably best explained with [a video](https://raw.githubusercontent.com/yourealwaysbe/video/master/splice.mp4).

You can first create an alternative segment in the usual way.  Then with the splicer, select the start and end points of the part of  the track/route you want to replace.  Then, click on the alternative segment.  The splicer will swap it in.

I'm doing this frequently when planning routes, so thought it would be useful to automate, instead of splitting and appending.

This has not yet been extensively tested, but behaves well with simple tests like splicing, not splicing a route into itself, handling deleting a route midway, zero and one length segments, repeated splices.  I'll do some route planning next week, so that'll give it a real world test.  In the meantime, i'll submit this for feedback and initial testing if you'd like to play.

### CODE REVIEW

**Comment by yourealwaysbe** [comment]
Actually, let's leave this on ice for a bit -- i have a better idea for a tool!

**Comment by rnorris** [comment]
Hmm, not sure where my original comment went, so here it's again & updated.

From my quick tests this looks interesting and something I'd use often.
I look forward to even a better tool!

I'm not quite sure how the travis tests pass, as it doesn't compile for me.
It looks like you forgot to update/commit _src/icons/Makefile.am_ to include the new filenames.

I also note that for a new tool & having a customised toolbar, one of course needs to manually add the tool into the toolbar. This should probably mentioned in the manual and if I remember, also in the release notes of a new version.

**Comment by yourealwaysbe** [comment]
Oops, i edited the wrong src/icons/Makefile!  #50 is the alternative tool.

**Comment by yourealwaysbe** [comment]
Variant merged as #53.

**Pull request closed without merging**
