### PR TITLE
Add filter box to track list on aggregate layers

### PR DESCRIPTION
**Pull request by yourealwaysbe**
Possibly addresses #78.
Searches in layer name, track/route name, comment, description, and date.

### CODE REVIEW

**Comment by rnorris** [comment]
This looks good.
I always had in mind something a bit more all singing and dancing (e.g. configurable to choose which fields to search on or not, maybe basic reg expressions, maybe date ranges, maybe length bounds for tracks or perhaps symbols for waypoints, etc, etc...) - but of course this is quite an effort so thus not implemented (nor likely to).

For each use of g_utf8_casefold() you need to free the returned string, which needs fixing before I merge this. i.e. for layer_name_case, trk_name_case, trk_comment_case and trk_description_case. ATM only the filter_case is freed.

Maybe move the layer_name and time_buf freeing to immediately after the end of their respective use rather than the end of the function?

NB I had a quick hack up of an equivalent waypoint search.
I found that searching for items was quick for up to about 1000 items (the largest track store I have), but starts to be noticeably slow down when several thousand items (some waypoint stores I have - the waypoint list dialog takes several seconds to open anyway in this case).
I think it has to call the filter function for every entry (at least on the first filter iteration), so I don't see an easy way to speed it up significantly.
I tried exiting the filter function early (i.e. goto end of the function when visibility is set to true) as don't need to bother with further tests; however this doesn't seem to make much difference, as overall it's the ones that don't match that take all the time.

Also could you change the
gtk_entry_new ();
-->
 ui_entry_new ( NULL, GTK_ENTRY_ICON_SECONDARY );

So that we get a click to clear the entered text option.

All in all great stuff!

**Comment by matthewhague** [comment]
Thanks for the feedback. I updated with the changes suggested (sorry for missing the frees!) and also copied it across to the waypoint list.

I noticed the same performance issues as you. However, these also seem to occur even if i set the filter callback to always immediately return TRUE. Perhaps filtering a tree view isn't the best way to go for a performant search facility.

**Comment by yourealwaysbe** [comment]
Thanks for the feedback. I updated with the changes suggested (sorry for missing the frees!) and also copied it across to the waypoint list.

I noticed the same performance issues as you. However, these also seem to occur even if i set the filter callback to always immediately return TRUE. Perhaps filtering a tree view isn't the best way to go for a performant search facility.

**Comment by rnorris** [comment]
> Perhaps filtering a tree view isn't the best way to go for a performant search facility.

Well it's an option over the default tree search which only matches from the beginning of the name

**Pull request merged**
