### PR TITLE
Add split-join tool

### PR DESCRIPTION
**Pull request by yourealwaysbe**
Easiest explained again with a [video](https://raw.githubusercontent.com/yourealwaysbe/video/master/split-join.mp4).

Useful for various track/route edits.  First click splits the track and
goes into track extension mode from the clicked point.  Second click on
a second track, splits it, and appends the continuation to the first
track.

After the first click, the track/route extension tools can be used.

Can be used to split tracks, append tracks (click on last and first
point), divert tracks through other tracks, or create shortcuts with the
track/route extension tools.

Yet to be fully tested, but submitting now for feedback.  Proposed instead of #48.

### CODE REVIEW

**Comment by yourealwaysbe** [comment]
Ah -- i should add a note about menu icons to the manual.  Will update later.

**Comment by Shura0** [comment]
Wow! Great tool.
But I would change behavior a bit. In last example you showed how to combine 'split-join' with 'create track' tool. It's very frustrating. Maybe 'split-join' should act like 'split-join-create'? I mean if user clicks on empty field it should create new points without tool 'create track'.

**Comment by guyou** [comment]
It seems really not natural to have to change tool while in edit action.

**Comment by guyou** [comment]
IMHO Viking already suffers to lack more classic idioms.

In many other tools handling graphical features like "path" such operations should be more intuitive.

To split a track, I should have a dedicated tool (just for that, like scissors) or to right-click and select "cut" in the contextual menu, then I should be able to click the last point of a track and simply continue it and when I click on the first point of another track, it naturally join them.

**Comment by yourealwaysbe** [comment]
How about merging the split-join into the new track/route tools, making a general edit tool. The behaviour would be:

Click, no current track: if on an existing track/route point, act as split-join. If elsewhere, create new track/route.

Click, with current track: if on an existing point, act as split-join. If elsewhere, add new point.

I can see an argument for a dedicated scissor tool, just for making the interface more intuitive. I have one implemented that i can dig out of git. It was while implementing these tools i realised they're all part of the same thing.

**Comment by rnorris** [comment]
ATM I like the 'split/join' tool.

Some things to consider for a general edit tool - as the track/route point area is quite small (and not configurable at the moment) it requires a precision click to select a desired point.
Thus with a general tool, if you miss the point it will add one (which then you'd have to delete - probably not too bad as you could right click to undo that add).
At least with specific split/join tool it wouldn't do anything if you miss slightly.

Where this could more be complicated is if one is creating new tracks on top of existing ones. You may or may not want it to split the existing ones. Thus having an explicit mode to split existing ones is good.

Of course one could also make the mode to engage in split/join behaviour explicit, such as when an modifier key is pressed (e.g. shift - since ctrl is already doing align to existing point request).

**Comment by yourealwaysbe** [comment]
I had already begun to notice the precision-click issue.  I hadn't though of plotting routes along existing tracks.  It's not a common use-case for me, but i can imagine a few situations where it might come up.  I had a go at it with #50, and it's a bit like tightrope walking.

I've done another version in #53 where shift has to be held.  This would be better if the cursor changed when shift was held, but i don't know how to do that right now.

**Comment by yourealwaysbe** [comment]
Variant merged as #53.

**Comment by yourealwaysbe** [comment]
Variant merged as #53.

**Comment by yourealwaysbe** [comment]
j

**Pull request closed without merging**
