### PR TITLE
Port to yelp-tools

### PR DESCRIPTION
**Pull request by City-busz**
This removes the usage of deprecated gnome-doc-utils.

### CODE REVIEW

**Comment by rnorris** [comment]
Thanks for this + fixing it so it works with the CI system. It certainly is desired to remove the need for gnome-doc-utils (and also scrollkeeper).

I'll need to confirm the Windows build still works too; as it doesn't need to run this (I think this was partially why GEN_MANPAGES was used)

Note some more lines in the README.md can probably be removed:
"Further packages are required if you want to generate man and help page documentation:
$ sudo apt-get install docbook-xsl rarian-compat"

In some respects I like having the 'docbook.xsl' file on the system, as it keeps the build self contained and doesn't require an internet connection (or the server on the other end to be available), but I'm not overly concerned with this bit.

**Comment by City-busz** [comment]
> In some respects I like having the 'docbook.xsl' file on the system, as it keeps the build self contained and doesn't require an internet connection (or the server on the other end to be available), but I'm not overly concerned with this bit.

It still uses the 'docbook.xsl' file on the system, and doesn't use internet. The '--nonet' option is still specified, so xsltproc detects the local copy of the stylesheet, but we don't have to guess the exact file path, and fails if missing. You can see [similar solutions](https://gitlab.gnome.org/GNOME/glade/-/blob/master/man/Makefile.am) in various GNOME projects.

Now I modified the README.md that docbook-xsl is a requirement (for the stylesheet), and rarian-compat is not needed.

**Comment by rnorris** [comment]
Ah, I did wonder how the '--nonet' jived with the http command line reference!

Sadly this didn't quite work out of the box for my Windows build, so a few tweaks can be done.

First I must mention the Windows build is performed as a cross build in custom VM based on OpenSUSE Tumbleweed (now some what old circa March 2018) as described in "windows/README.txt".
Ideally I'd like to have an automated Windows CI build such as via appveyor; but that is not been done yet.

So first the addition of YELP_HELP_INIT, means at least two more programs are needed in the build system (itstool & xmllint). Neither of these seemed to be available to install in my VM (although available in OpenSUSE itself with xmllint under the package libxml-tools).

Thus it seems simplest to not do help things under Windows (as it doesn't use this help system ATM anyway), so for the **configure.ac**:

    -YELP_HELP_INIT
    +if test "x$ac_cv_enable_windows" = "xno"; then
    +  YELP_HELP_INIT
    +fi

Next although my VM has xsltproc + docbook-xsl, it failed to find the docbook.xsl file and couldn't download it either.
So I think its simpler just skip the 'help' build on windows, thus for **Makefile.am**:

    -SUBDIRS = src test data po windows help tools doc
    +SUBDIRS = src test data po windows tools doc
    +if !WINDOWS
    +SUBDIRS += help
    +endif

We can also improve both file **mingw-viking.spec.in** & **mingw64-viking.spec.in** used for the Windows build by ensuring the VM has xsltproc:

So add the additional requirement:

    +BuildRequires: libxslt-tools

And now as scrollkeeper is not used anywhere we can remove the disabling of it line too:

    -  --disable-scrollkeeper \

Also as you changed the filename viking.xml -> index.docbook, we should update the **help/C/README.txt** appropriately for the filename change and note that the pdf generation command is now:

    -dblatex viking.xml
    +dblatex index.docbook -o viking.pdf

HTH

Maybe I'll investigate deploying yelp in the Windows installer, so I can remove the ShellExecute() for the pdf in vikwindow.c, but that is a separate issue. Even then the build system doesn't need to do anything in the help directory - it would all be in the Windows installer.

**Comment by rnorris** [comment]
This has now been merged into the master code base.

**Pull request closed without merging**
