### PR TITLE
Add Github Actions Workflow

### PR DESCRIPTION
**Pull request by guyou**
GitHub has a quite good CI system.

### CODE REVIEW

**Comment by rnorris** [comment]
Welcome back!

This will be good when complete.

NB It would be nice if all the individual commits get compressed into one, as probably unnecessary to have a development history in the main repository. I might manually do this once work is complete to merge into the mainline.

**Comment by guyou** [comment]
> Welcome back!

Thanks!

> This will be good when complete.

I'm not sure of the really first goal to achieve. Probably only the current state: a build+test on each push + PR. Possibly a build on Windows? Should we still need a matrix build with many linux flavors and variable configurations (`--with-XXX`)?

In the future, perhaps helping to release: at work we now use a manual job to trigger an automatic release with semantic-release (when clicked, semantic-release analyse commits and decide the new version number, generate the ChangeLog and commit+tag). On tag, the product is built and published automatically.

> NB It would be nice if all the individual commits get compressed into one, as probably unnecessary to have a development history in the main repository. I might manually do this once work is complete to merge into the mainline.

Yes, you're right.

**Comment by rnorris** [comment]
I think the first goal is to restore the capability previously done under Travis, thus I think it was a CI build+test on each main branch push and PRs.

Then depending on the amount of compute offered via the Github workflow services, perform a test build of every optional disable-XX component (build only - i.e. no test - as ATM the tests assume a fully capable Viking).
Previously IIRC the .travis config did some build variants but not all, as otherwise we ran out of compute resources.

Ideally it would be good to create an auto Windows build, IMHO creating an MS Visual Studio Solution isn't the hard part, but the (auto/defining) installing the dependent components in the Windows system is. I've not found a similar project that we could take inspiration from :( - various other projects use different build systems CMake, Meson, etc...

Unfortunately, currently the github action workflow doesn't offer OpenSUSE Linux (as then could perform the Cross Build that I do manually as explained in the source code `windows/README.txt`).
For example, e.g.  `Geany` - performs a cross build, but maintains their own Docker image instance - which is invoked via a custom github action workflow. Unknown to me what is in their Docker image, how it is setup, who hosts it and so on.

Since we don't do that many releases, a much more automated release isn't a priority. But interesting nevertheless. Possibly would want to tag commits more semantically e.g. so new features could be identified and promoted versus the churn of smaller internal code improvements, etc...

**Comment by rnorris** [comment]
Consider changing in the `help/Makefile.am`  file from:

    XSLTPROC=@XSLTPROC@ -''-nonet

to

    XSLTPROC=@XSLTPROC@ -nonet

I've no idea why that `-''` is there, seems to be superfluous - and removing it still generates help OK on my machine,  so might fix the last build failure under the workflow/Ubuntu

**Comment by guyou** [comment]
I did the change you suggested, but it is still failing:
https://github.com/guyou/viking/actions/runs/5740958252/job/15559965113

It needs more investigations.

**Comment by guyou** [comment]
It is suspicious: it already passed as it failed at `check` stage: https://github.com/guyou/viking/actions/runs/5726926487/job/15518533551

**Comment by guyou** [comment]
OK, I think I found: I removed the caches and it passes (until the check).

I used an Action to cache the apt installations, but it fails: some packages are not correctly restored.

I will replace this action.

**Comment by guyou** [comment]
@rnorris I have better success now, even in native (without Docker). But tests are failing due to poor display (xvfb), I suspect.

What do we do? Do we merge current, with failures? Do we remove tests from CI? Do we revise code to have tests passing even with xvfb?

**Comment by rnorris** [comment]
To be honest I am quite happy with the tests working on one's desktop - it is a GUI program after all!

If the CI can not be (easily/within reason) made to work or if many tests have to be disabled under CI - it rather defeats the purpose of this CI in the first place.

So I think the CI work should only be merged when it says it is 'passing'.

Part of the trouble presumably is with the 'make check' is that it is all or nothing; and the 'check' is actually doing a load of automatic things for you - so customizing for different situations needs a better understanding (or even if it is possible).
If one could easily do a 'make check-subset-for-CI' somehow then it would be useful.

At least your current work provides a baseline that we can take forward in the future.

**Comment by rnorris** [comment]
Closing this issue since Github Workflows are now in the mainline

**Pull request closed without merging**
