### PR TITLE
Draw overlays on track graphs as line

### PR DESCRIPTION
**Pull request by yourealwaysbe**
Rather than scattered points. I find this easier to make sense of, though it's not great the same logic ended up being repeated 4 times.

Here is a screenshot.

sway-shot

### CODE REVIEW

**Comment by rnorris** [comment]
Yes agreed it's visually better - especially on routes where there can be relatively few points.

Previously was drawing rectangles of 4x4 - so could be equivalent of line width of 4; but now it uses a width of 2 - which is arguably better anyway.

Regarding the repeated same logic - some other options that come to my mind would introduce different complexities - so this can suffice as is.

Some things I've noticed but aren't just this patch which - there needs more consideration for high resolution display support.
Currently there are a few places where the width/size of lines/rectangles needs multiplying by the viewport scale and a place where it should reset the line width.

I'm currently leaning towards including this now and so be in upcoming v1.9.1 - hopefully this month.

**Comment by rnorris** [comment]
I've just noticed this doesn't compile under GTK2 - as 'first_point_speed' is undeclared.
Either enclose the final usage of 'first_point_speed' in a GTK3 ifdef block (similar to 'first_point_alt' is handled above); or perhaps move the declaration of first_point_* variables to be outside the GTK3 only part, such that the last usage of them don't need to be in an ifdef GTK3 only part - with the idea to help try and limit the number of ifdefs.

**Comment by yourealwaysbe** [comment]
I force-pushed a fix to the GTK2 error -- sorry for not catching that.

I'm happy to make fixes for high-resolution displays if there's a "viking" approach to that.

**Comment by rnorris** [comment]
No worries about not noticing the GTK2 error - I didn't see it for a while too.
And this is what peer review is for :)

So instead of a fixed pixel size (or offset) - these values should be multiplied by vik_viewport_get_scale(vvp).
This is normally 1, so makes no difference. But for a high resolution display the get_scale() should return 2.

This is not so bad for line widths as this is set more or less just the once.
But for some rectangle drawings the multiplier should be used in both the x & y offsets - which makes the gdk_draw_rectangle() usage some what more long winded.

However in your patch to use proper lines - in the GTK3 version at least - rather than a series of rectangles anyway.

So for this patch modify the new instances of:
     `cairo_set_line_width ( cr, GRAPH_OVERLAY_LINE_WIDTH );`
-->
     `cairo_set_line_width ( cr, GRAPH_OVERLAY_LINE_WIDTH * vik_viewport_get_scale(widgets->vvp) );`

**Comment by rnorris** [comment]
Columbo style: Just more one thing...

I noticed the this doesn't draw the first line between the first two points - which is much more noticeable when creating a route, than viewing an existing track (since the track will have hundreds of points and so the first line is going to be very short).

In fact the current version doesn't draw a rectangle on the very first trackpoint, since the loop here is starting on the second trackpoint -> for (iter = tr->**trackpoints->next**; iter; iter = iter->next)
In order to calculate a distance difference to the previous trackpoint.

So I think one can:
1. Set defaults for the last values - which is used if when no elevation values are available.
     `gboolean last_available_alt = FALSE;`

2. Work out the coordinate for the first trackpoint explicitly:
`  // Handle first trackpoint to set the 'last' values`
`  if ( do_dem ) {`
`    gint16 elev = a_dems_get_elev_by_coord ( &(VIK_TRACKPOINT(tr->trackpoints->data)->coord), VIK_DEM_INTERPOL_BEST );`
`    if ( elev != VIK_DEM_INVALID_ELEVATION ) {`
`        // Convert into height units`
`        if (a_vik_get_units_height () == VIK_UNITS_HEIGHT_FEET)`
`            elev =  VIK_METERS_TO_FEET(elev);`
`            elev -= alt_offset;`
`            last_y_alt = h2 - ((height * elev)/achunk);`
`            last_x_alt = margin;`
`            last_available_alt = TRUE;`
`        }`
`  }`
 
3. Instead of `first_point_alt` track when the last values are valid and only draw the line when the last values are available.

4. Speed could be handled similarly

**Comment by yourealwaysbe** [comment]
Sorry for the delay. I've adapted `draw_dem_alt_speed_dist` to iterate over all points, not just from the second onwards. The dist calculation at the start was, as far as i could tell, only to determine where to draw the point. Just checking if it's the first point and leaving dist at 0 if it was seemed to be enough.

I also added a line_width parameter for GTK3 so that it could scale for hidef displays.

**Comment by rnorris** [comment]
I took the liberty of manually combining these commits into one. (Hopefully I got it right!)

**Comment by yourealwaysbe** [comment]
> I took the liberty of manually combining these commits into one. (Hopefully I got it right!)

Great, thanks. That's what i was hoping you'd do :)

**Pull request closed without merging**
